### ISSUE TITLE
Request assistance for annotated mouse brain transcriptome data

### ISSUE THREAD

**Issue by tqwang743** [bsungwoo/spSeudoMap#3]
Hi,

It is a fantastic method for analyzing spatial transcriptomics!

I also conduct research on the V1_Adult_Mouse_Brain_Coronal_Section_1 dataset. I have carefully read your article and noticed that you have labeled the mouse brain spatial transcriptome data using the following method.
<img width="401" alt="image" src="https://github.com/user-attachments/assets/130e5f1b-000a-4846-a9e2-a92ef824e98e">
I believe this is an excellent approach, and I would greatly appreciate it if you could provide the annotated mouse brain spatial transcriptome data or the code to implement this method. Thank you very much!

Best Regrads,
tqwang

**Comment by bsungwoo** [comment]
@tqwang743 
Thank you for your interest in our tool. Please find attached a link to the .rds and .h5ad files used for the analysis. Please refer to the metadata or obs for the column name 'cluster_rename', which indicates the annotation label for the spot clusters.
Link: [mouse_brain_coronal](https://drive.google.com/drive/folders/1oVFh2N8hFRt8zXks1niMDier1xDu5geK?usp=drive_link)

**Comment by tqwang743** [comment]
Sorry for not replying to your message in time, I download the labeled dataset through your link, thank you very much for your help！
